apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: pod-must-have-app-label
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    # List namespaces to ignore
    excludedNamespaces:
      - "kube-system"
      - "gatekeeper-system"
      - "monitoring"
  parameters:
    labels: ["app"]
