apiVersion: loom.rickliujh.github.io/v1beta1
kind: Loom
metadata:
  name: onboard-service
spec:
  params:
    - name: serviceName
      required: true
    - name: namespace
      default: "default"
    - name: commitHash
      dynamic: "git rev-parse --short HEAD"
  target:
    url: "git@github.com:rickliujh/loom-test.git"
    branch: "main"
    featureBranch: "loom/test-{{ .serviceName }}"
  operations:
    - name: create-files
      newFiles:
        source: "."
        dest: ""
    # - name: patch-app
    #   patch:
    #     engine: json6902
    #     path: "__functions/patches/add-app.yaml"
    #     target: "cluster/constraints/cluster-secret-store-control.yaml"
    - name: patch-clsuter-secret-store
      patch:
        path: "__functions/patches/clustersecretstore-patch.yaml"
        target: "cluster/constraints/cluster-secret-store-control.yaml"
    - name: validate
      shell:
        command: "echo 'validating {{ .serviceName }} in {{ .namespace }}'"
        timeout: "30s"
    - name: commit
      commitPush:
        message: "feat: loom test {{ .serviceName }}"
        # author: "loom-bot"
        # email: "loom@example.com"
    - name: open-pr
      pr:
        provider: github
        title: "loom test pr {{ .serviceName }}"
        baseBranch: main
        labels: [automated]
        tokenEnv: GITHUB_TOKEN
